apiVersion: apps/v1
kind: Deployment
metadata:
  name: chichilanding
  labels:
    app: chichilanding
spec:
  replicas: 1
  template:
    metadata:
      name: chichilanding
      labels:
        app: chichilanding
    spec:
      containers:
        - name: chichilanding
          image: includeamin/chichilanding:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      restartPolicy: Always
  selector:
    matchLabels:
      app: chichilanding
