apiVersion: apps/v1
kind: Deployment
metadata:
  name: chichiapp.ir
spec:
  selector:
    matchLabels:
      app: chichiapp.ir
  template:
    metadata:
      labels:
        app: chichiapp.ir
    spec:
      containers:
      - name: chichiapp.ir
        image: includeamin/chichiapp.ir:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
