apiVersion: v1
kind: Service
metadata:
  name: chichilanding
spec:
  selector:
    app: chichilanding
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32030
      protocol: TCP
      name: chichilanding
  type: NodePort
