apiVersion: v1
kind: Service
metadata:
  name: chichilanding
spec:
  selector:
    app: chichilanding
  ports:
    - port: 3000
      targetPort: 3800
      nodePort: 38030
      protocol: TCP
      name: chichilanding
  type: NodePort